# Generated by Django 4.0.6 on 2022-07-13 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, upload_to='users/cover/', verbose_name='Kapak Fotosu')),
                ('avatar', models.ImageField(blank=True, upload_to='users/avatar/', verbose_name='Avatar')),
                ('first_name', models.CharField(max_length=20, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=20, verbose_name='Soyadı')),
                ('gender', models.CharField(choices=[('', '------'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın'), ('Belirtmek istemiyorum', 'Belirtmek istemiyorum')], default='', max_length=30, verbose_name='Cinsiyet')),
                ('address', models.TextField(verbose_name='Adres')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Yaşadığı şehir')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('about', models.TextField(blank=True, verbose_name='Hakkımda')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Meslek')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Telefon')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi:')),
                ('skils', models.CharField(blank=True, max_length=200, verbose_name='Yetenekler')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='İnstagram')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Katılma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
                'db_table': 'accounts',
            },
        ),
    ]
