# Generated by Django 4.0.6 on 2022-07-11 15:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Koşul ve Şartlar')),
                ('terms', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Koşul ve Şartlar')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gönderilme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Koşul ver Şartlar',
                'verbose_name_plural': 'Koşul ver Şartlar',
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'ordering': ['publish'], 'verbose_name': 'Üst Kapak', 'verbose_name_plural': 'Üst Kapak'},
        ),
    ]
